services:

  lint:
    image: "test-puppet-puma"
    build: "."
    volumes:
      # Code
      - "./manifests:/test/manifests"
    command: "bundle exec rake lint"

  validate:
    image: "test-puppet-puma"
    build: "."
    volumes:
      # Code
      - "./manifests:/test/manifests"
    command: "bundle exec rake validate"
