version: 2

jobs:
  test-puppet3: &test_setup
    working_directory: ~/puppet-puma
    docker:
      - image: ruby:2.1  # puppet 3 is incompatible with ruby 2.2+
        environment:
          BUNDLE_GEMFILE: Gemfile3
    steps:
      - checkout
      - run:
          name: Install RubyGem dependencies
          command: bundle install --path=vendor/bundle --jobs=4 --retry=3
      - run:
          name: Linter and Parser
          command: bundle exec rake lint
      - run:
          name: Unit tests
          command: bundle exec rake validate

  test-puppet4:
    <<: *test_setup
    docker:
      - image: ruby:2.4-jessie
        environment:
          BUNDLE_GEMFILE: Gemfile4

  test-puppet5:
    <<: *test_setup
    docker:
      - image: ruby:2.4-jessie
        environment:
          BUNDLE_GEMFILE: Gemfile5

workflows:
  version: 2
  test-workflow:
    jobs:
      - test-puppet3:
      - test-puppet4:
      - test-puppet5:
