name: test-openvox8

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  test-puppet8:
    runs-on: ubuntu-latest
    container:
      image: ruby:3.4.10-bookworm
    steps:
      - uses: actions/checkout@v5

      - name: Install RubyGem dependencies
        run: bundle install --jobs=4 --retry=3
        env:
          BUNDLE_GEMFILE: Gemfile8

      - name: Openvox lint
        run: bundle exec rake lint

      - name: Puppet/openvox parser validation
        run: bundle exec rake validate
